//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_LPPA.Models.LPPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public System.Guid Id_permiso { get; set; }
        public string Permiso1 { get; set; }
    }
}
